#!/bin/bash
cd $BIOPERF/Binaries/x86-Binaries/Predator
./predator $BIOPERF/Inputs/Predator/class-A/Q89F91 -u -h -a -f$BIOPERF/Outputs/Predator/classA-predator
echo The output has been stored as classA-predator in $BIOPERF/Outputs/Predator
cd $BIOPERF/Binaries/x86-Binaries/Predator
./predator $BIOPERF/Inputs/Predator/class-B/eukaryota_100.seq -u -h -a -f$BIOPERF/Outputs/Predator/classB-predator
echo The output has been stored as classB-predator in $BIOPERF/Outputs/Predator
cd $BIOPERF/Binaries/x86-Binaries/Predator
./predator $BIOPERF/Inputs/Predator/class-C/largeinput -u -h -a -f$BIOPERF/Outputs/Predator/classC-predator
echo The output has been stored as classC-predator in $BIOPERF/Outputs/Predator
