#!/bin/bash 
source $HOME/.bioperf
cd $BIOPERF/Binaries/x86-Binaries/Glimmer
./glimmer2 $BIOPERF/Inputs/Glimmer/class-A/NC_004061.fna  $BIOPERF/Binaries/x86-Binaries/Glimmer/glimmer.icm > $BIOPERF/Outputs/Glimmer/glimmer-classA.output
echo The output has been stored as glimmer-classA.output in $BIOPERF/Outputs/Glimmer
./glimmer2 $BIOPERF/Inputs/Glimmer/class-B/NC_003062.fna  $BIOPERF/Binaries/x86-Binaries/Glimmer/glimmer.icm > $BIOPERF/Outputs/Glimmer/glimmer-classB.output
echo The output has been stored as glimmer-classB.output in $BIOPERF/Outputs/Glimmer
./glimmer2 $BIOPERF/Inputs/Glimmer/class-C/NC_004463.fna  $BIOPERF/Binaries/x86-Binaries/Glimmer/glimmer.icm > $BIOPERF/Outputs/Glimmer/glimmer-classC.output
echo The output has been stored as glimmer-classC.output in $BIOPERF/Outputs/Glimmer

