#!/bin/bash 
source $HOME/.bioperf
cd $BIOPERF/Binaries/PowerPc-Binaries/Tcoffee/
export CLUSTALW_4_TCOFFEE=$BIOPERF/Binaries/PowerPc-Binaries/Clustalw/clustalw
#export CLUSTALW_4_TCOFFEE
export LALIGN_4_TCOFFEE=$BIOPERF/Binaries/PowerPc-Binaries/Tcoffee/lalign2list
#export LALIGN_4_TCOFFEE
./t_coffee $BIOPERF/Inputs/Tcoffee/class-A/1amk_ref1.pep
mv *.aln *.dnd $BIOPERF/Outputs/Tcoffee/
echo The output has been stored as *.aln and *.dnd in /Outputs/Tcoffee
