#!/bin/bash 
source $HOME/.bioperf
cd $BIOPERF/Binaries/x86-Binaries/Clustalw
./clustalw -batch -infile=$BIOPERF/Inputs/Clustalw/class-A/1a02J_1hjbA
mv $BIOPERF/Inputs/Clustalw/class-A/1a02J_1hjbA.aln $BIOPERF/Inputs/Clustalw/class-A/1a02J_1hjbA.dnd  $BIOPERF/Outputs/Clustalw/
echo The output has been stored as 1a2J_1hjbA.dnd and 1a2J_1hjbA.aln has been stored in $BIOPERF/Outputs/Clustalw
cd $BIOPERF/Binaries/x86-Binaries/Clustalw
./clustalw -batch -infile=$BIOPERF/Inputs/Clustalw/class-B/1290.seq
mv $BIOPERF/Inputs/Clustalw/class-B/1290.aln $BIOPERF/Inputs/Clustalw/class-B/1290.dnd  $BIOPERF/Outputs/Clustalw/
echo The output has been stored as 1290.dnd and 1290.aln has been stored in 
$BIOPERF/Outputs/Clustalw 
cd $BIOPERF/Binaries/x86-Binaries/Clustalw
./clustalw -batch -infile=$BIOPERF/Inputs/Clustalw/class-C/6000.seq
mv $BIOPERF/Inputs/Clustalw/class-C/6000.aln $BIOPERF/Inputs/Clustalw/class-C/6000.dnd  $BIOPERF/Outputs/Clustalw/
echo The output has been stored as 6000.dnd and 6000.aln in $BIOPERF/Outputs/Clustalw
