#!/bin/bash 
source $HOME/.bioperf 
input=$BIOPERF/Inputs/Glimmer/class-C/NC_004463.fna
cd $BIOPERF/Binaries/PowerPc-Binaries/Glimmer
echo "run Glimmer2"
clear
echo "Genome is NC_004463.fna" 
echo "Find non-overlapping orfs in  tmp.coord"
rm -f tmp.coord
./long-orfs $input | ./get-putative >tmp.coord
echo "Extract training sequences to  tmp.train"
rm -f tmp.train
./extract $input tmp.coord >tmp.train
wc tmp.train
echo "Build interpolated context model in  tmp.model"
rm -f tmp.model
./build-icm <tmp.train >tmp.model
echo "Predict genes with Glimmer2 with coordinates in  g2.coord"
rm -f g2.coord
./glimmer2 $input tmp.model | ./get-putative > $BIOPERF/Outputs/Glimmer/glimmer-package-classC.output
rm tmp*
echo The output has been stored as glimmer-package-classC.output in $BIOPERF/Outputs/Glimmer


