#!/bin/bash 
source $HOME/.bioperf
cd $BIOPERF/Binaries/PowerPc-Binaries/Phylip
file=$BIOPERF/Binaries/PowerPc-Binaries/Phylip/infile
if [ -r $file ]
then 
echo Deleting previous infile in the Binary directory
rm $file
ln -s $BIOPERF/Inputs/Phylip/dnapenny/infile.dnapenny $BIOPERF/Binaries/PowerPc-Binaries/Phylip/infile
else 
ln -s $BIOPERF/Inputs/Phylip/dnapenny/infile.dnapenny $BIOPERF/Binaries/PowerPc-Binaries/Phylip/infile
fi

file2=$BIOPERF/Binaries/PowerPc-Binaries/Phylip/outfile
file3=$BIOPERF/Binaries/PowerPc-Binaries/Phylip/outtree

if [ -r $file2 ] 
then 
rm $file2
fi

if [ -r $file3 ]
then 
rm $file3
fi
./dnapenny 
mv $file2  $BIOPERF/Outputs/Phylip/dnapenny-outfile
mv $file3  $BIOPERF/Outputs/Phylip/dnapenny-outtree
#Notes:
#1.Please make sure to delete outfile and outtree before repeating the program. Otherwise,the program will not run again successfully.
#2.Please check ./phylip-3.6/exe/infile.dnapenny to assure it to point to the correct path of infile.dnapenny.
