>1rms
saeytcgstcywssdvsaakakgyslyesgdtiddypheyhdyegfdfpv
sgtyyeypimsdydvytggspgadrvifngddelagvithtgasgddfva
c
>1fus
attcgstnysasqvraaanaacqyyqnddtasstyphtynnyegfdfpvd
gpyqefpiksggvytggspgadrvvintnbeyagaithtgasgnnfvga
>rnn1_neucr
acmyicgsvcysssaisaalnkgysyyedgatagsssyphrynnyegfdf
ptakpwyefpilssgrvytggspgadrvifdshgnldmlithngasgnnf
vac
>rnt1_triha
tcgkvfysasavsaasnaacnyvragstaggstyphvynnyegfrfkgls
kpfyefpilssgktytggspgadrvvingqcsiagiithtgasgnafvac

>rnu1_ustsp
cggtyysstqvnrainnaksgqysstgyphtynnyegfdfsdycdgpyke
yplktsssgytggspgadrvvydsndgtfcgaithtgasgnnfvqc
