#!/bin/bash 
source $HOME/.bioperf
cd $BIOPERF/Binaries/x86-Binaries/Tcoffee/
export CLUSTALW_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Clustalw/clustalw
#export CLUSTALW_4_TCOFFEE
export LALIGN_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Tcoffee/lalign2list
#export LALIGN_4_TCOFFEE
./t_coffee $BIOPERF/Inputs/Tcoffee/class-A/1amk_ref1.pep
mv *.aln *.dnd $BIOPERF/Outputs/Tcoffee/
echo The output has been stored as *.aln and *.dnd in $BIOPERF/Outputs/Tcoffee
cd $BIOPERF/Binaries/x86-Binaries/Tcoffee/
export CLUSTALW_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Clustalw/clustalw
#export CLUSTALW_4_TCOFFEE
export LALIGN_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Tcoffee/lalign2list
#export LALIGN_4_TCOFFEE
./t_coffee $BIOPERF/Inputs/Tcoffee/class-B/2scuA_1drw
mv *.aln *.dnd $BIOPERF/Outputs/Tcoffee/
echo The output has been stored as *.aln and *.dnd in $BIOPERF/Outputs/Tcoffee
cd $BIOPERF/Binaries/x86-Binaries/Tcoffee/
export CLUSTALW_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Clustalw/clustalw
#export CLUSTALW_4_TCOFFEE
export LALIGN_4_TCOFFEE=$BIOPERF/Binaries/x86-Binaries/Tcoffee/lalign2list
#export LALIGN_4_TCOFFEE
./t_coffee $BIOPERF/Inputs/Tcoffee/class-C/1yge_1byt
mv *.aln *.dnd $BIOPERF/Outputs/Tcoffee/
echo The output has been stored as *.aln and *.dnd in $BIOPERF/Outputs/Tcoffee  
